### ISSUE TITLE
复现相关咨询

### ISSUE THREAD

**Issue by LinJFDaDa** [cnuzh/LG-GNN#5]
非常感谢您的代码，对我学习非常有帮助！想请教您一个问题，该论文采用的是节点特征是每个roi对应的与其他roi皮尔逊相关组成的向量吗，我采用此方法，十折最高只能在测试集上达到70%左右的精度，非常期待您的指导和答复！

**Comment by zzjkh** [comment]
你好，我也在尝试复现该代码，但是对于数据部分有些疑惑，请问实验使用具体的rsfmri数据和预处理流程是什么样的？万分感谢

**Comment by ShenAoChen2001** [comment]
> 非常感谢您的代码，对我学习非常有帮助！想请教您一个问题，该论文采用的是节点特征是每个roi对应的与其他roi皮尔逊相关组成的向量吗，我采用此方法，十折最高只能在测试集上达到70%左右的精度，非常期待您的指导和答复！

你好，我也在复现这篇论文，我也只能达到类似的效果，希望我们可以交流交流？
![image](https://github.com/user-attachments/assets/3f85b1c6-cb51-4a3f-8a1e-e5443fef545b)

**Comment by jadeylove** [comment]
@ShenAoChen2001 你好请问你有遇到这个报错吗，该怎么改呀Traceback (most recent call last):
  File "main.py", line 25, in <module>
    raw_features, y, nonimg, phonetic_score = dl.load_data()
  File "/mnt/workspace/LG-GNN/util.py", line 37, in load_data
    labels = get_subject_score(subject_IDs, score='Group')
  File "/mnt/workspace/LG-GNN/util.py", line 125, in get_subject_score
    if row['Image Data ID'][1:] in subject_list:  
KeyError: 'Image Data ID'

**Comment by ShenAoChen2001** [comment]
你好，应该是你那个excel里面的ID这一列不叫这个名字，我这边就不叫这个




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月22日(星期五) 中午12:21
收件人: ***@***.***&gt;; 
抄送: "(12N15L24) ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cnuzh/LG-GNN] 复现相关咨询 (Issue #5)














 
@ShenAoChen2001 你好请问你有遇到这个报错吗，该怎么改呀Traceback (most recent call last):
 File "main.py", line 25, in 
 raw_features, y, nonimg, phonetic_score = dl.load_data()
 File "/mnt/workspace/LG-GNN/util.py", line 37, in load_data
 labels = get_subject_score(subject_IDs, score='Group')
 File "/mnt/workspace/LG-GNN/util.py", line 125, in get_subject_score
 if row['Image Data ID'][1:] in subject_list:
 KeyError: 'Image Data ID'

**Comment by jadeylove** [comment]
方便分享一下你的csv表格吗，abide的

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："ShenAoChen2001 ***@***.***&gt;;
发送时间：2024年11月22日(星期五) 下午3:33
收件人："cnuzh/LG-GNN" ***@***.***&gt;;
抄送："李成轩 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [cnuzh/LG-GNN] 复现相关咨询 (Issue #5)
-----------------------------------

 

 你好，应该是你那个excel里面的ID这一列不叫这个名字，我这边就不叫这个 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2024年11月22日(星期五) 中午12:21 
 收件人: ***@***.***&amp;gt;;  
 抄送: "(12N15L24) ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [cnuzh/LG-GNN] 复现相关咨询 (Issue #5) 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
   
 @ShenAoChen2001 你好请问你有遇到这个报错吗，该怎么改呀Traceback (most recent call last): 
  File "main.py", line 25, in  
  raw_features, y, nonimg, phonetic_score = dl.load_data() 
  File "/mnt/workspace/LG-GNN/util.py", line 37, in load_data 
  labels = get_subject_score(subject_IDs, score='Group') 
  File "/mnt/workspace/LG-GNN/util.py", line 125, in get_subject_score 
  if row['Image Data ID'][1:] in subject_list: 
  KeyError: 'Image Data ID'

**Comment by ShenAoChen2001** [comment]
我们为什么不加个好友呢？在这发邮件哈哈哈哈哈




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "cnuzh/LG-GNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月22日(星期五) 下午3:37
***@***.***&gt;;
抄送:&nbsp;"(12N15L24) ***@***.******@***.***&gt;;
主题:&nbsp;Re: [cnuzh/LG-GNN] 复现相关咨询 (Issue #5)





 方便分享一下你的csv表格吗，abide的 
 
 ---------- 
 
 该邮件从移动设备发送 
 
 
 --------------原始邮件-------------- 
 发件人："ShenAoChen2001 ***@***.***&amp;gt;; 
 发送时间：2024年11月22日(星期五) 下午3:33 
 收件人："cnuzh/LG-GNN" ***@***.***&amp;gt;; 
 抄送："李成轩 ***@***.***&amp;gt;;"Comment ***@***.***&amp;gt;; 
 主题：Re: [cnuzh/LG-GNN] 复现相关咨询 (Issue #5) 
 ----------------------------------- 
 
   
 
  你好，应该是你那个excel里面的ID这一列不叫这个名字，我这边就不叫这个  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2024年11月22日(星期五) 中午12:21  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: "(12N15L24) ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [cnuzh/LG-GNN] 复现相关咨询 (Issue #5)  
   
   
   
   
   
   
   
   
   
   
   
   
   
   
     
  @ShenAoChen2001 你好请问你有遇到这个报错吗，该怎么改呀Traceback (most recent call last):  
   File "main.py", line 25, in   
   raw_features, y, nonimg, phonetic_score = dl.load_data()  
   File "/mnt/workspace/LG-GNN/util.py", line 37, in load_data  
   labels = get_subject_score(subject_IDs, score='Group')  
   File "/mnt/workspace/LG-GNN/util.py", line 125, in get_subject_score  
   if row['Image Data ID'][1:] in subject_list:  
   KeyError: 'Image Data ID'

**Comment by jadeylove** [comment]
好滴，扣扣1211758727

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："ShenAoChen2001 ***@***.***&gt;;
发送时间：2024年11月22日(星期五) 下午3:33
收件人："cnuzh/LG-GNN" ***@***.***&gt;;
抄送："李成轩 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [cnuzh/LG-GNN] 复现相关咨询 (Issue #5)
-----------------------------------

 

 你好，应该是你那个excel里面的ID这一列不叫这个名字，我这边就不叫这个 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2024年11月22日(星期五) 中午12:21 
 收件人: ***@***.***&amp;gt;;  
 抄送: "(12N15L24) ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [cnuzh/LG-GNN] 复现相关咨询 (Issue #5) 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
   
 @ShenAoChen2001 你好请问你有遇到这个报错吗，该怎么改呀Traceback (most recent call last): 
  File "main.py", line 25, in  
  raw_features, y, nonimg, phonetic_score = dl.load_data() 
  File "/mnt/workspace/LG-GNN/util.py", line 37, in load_data 
  labels = get_subject_score(subject_IDs, score='Group') 
  File "/mnt/workspace/LG-GNN/util.py", line 125, in get_subject_score 
  if row['Image Data ID'][1:] in subject_list: 
  KeyError: 'Image Data ID'

**Comment by ShenAoChen2001** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cnuzh/LG-GNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月22日(星期五) 下午3:37
***@***.***&gt;;
抄送:&nbsp;"(12N15L24) ***@***.******@***.***&gt;;
主题:&nbsp;Re: [cnuzh/LG-GNN] 复现相关咨询 (Issue #5)





 方便分享一下你的csv表格吗，abide的 
 
 ---------- 
 
 该邮件从移动设备发送 
 
 
 --------------原始邮件-------------- 
 发件人："ShenAoChen2001 ***@***.***&amp;gt;; 
 发送时间：2024年11月22日(星期五) 下午3:33 
 收件人："cnuzh/LG-GNN" ***@***.***&amp;gt;; 
 抄送："李成轩 ***@***.***&amp;gt;;"Comment ***@***.***&amp;gt;; 
 主题：Re: [cnuzh/LG-GNN] 复现相关咨询 (Issue #5) 
 ----------------------------------- 
 
   
 
  你好，应该是你那个excel里面的ID这一列不叫这个名字，我这边就不叫这个  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2024年11月22日(星期五) 中午12:21  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: "(12N15L24) ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [cnuzh/LG-GNN] 复现相关咨询 (Issue #5)  
   
   
   
   
   
   
   
   
   
   
   
   
   
   
     
  @ShenAoChen2001 你好请问你有遇到这个报错吗，该怎么改呀Traceback (most recent call last):  
   File "main.py", line 25, in   
   raw_features, y, nonimg, phonetic_score = dl.load_data()  
   File "/mnt/workspace/LG-GNN/util.py", line 37, in load_data  
   labels = get_subject_score(subject_IDs, score='Group')  
   File "/mnt/workspace/LG-GNN/util.py", line 125, in get_subject_score  
   if row['Image Data ID'][1:] in subject_list:  
   KeyError: 'Image Data ID'

**Comment by CangHZ** [comment]
@ShenAoChen2001 你好，你们复现的问题解决了吗，可以交流一下

**Comment by ShenAoChen2001** [comment]
目前来说应该是解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cnuzh/LG-GNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月3日(星期二) 中午11:21
***@***.***&gt;;
抄送:&nbsp;"(12N15L24) ***@***.******@***.***&gt;;
主题:&nbsp;Re: [cnuzh/LG-GNN] 复现相关咨询 (Issue #5)





 
@ShenAoChen2001 你好，你们复现的问题解决了吗，可以交流一下

**Comment by 78551** [comment]
或许有人加个联系方式交流一下吗

**Comment by zzjkh** [comment]
> > 你好，我也在尝试复现该代码，但是对于数据部分有些疑惑，请问实验使用具体的rsfmri数据和预处理流程是什么样的？万分感谢
> 
> 你好我也在复现这个代码，可以加联系方式交流一下吗微信785517067

您是遇到了什么问题吗，我现在已经不再尝试复现该代码

**Comment by 78551** [comment]
> > > 你好，我也在尝试复现该代码，但是对于数据部分有些疑惑，请问实验使用具体的rsfmri数据和预处理流程是什么样的？万分感谢
> > 
> > 
> > 你好我也在复现这个代码，可以加联系方式交流一下吗微信785517067
> 
> 您是遇到了什么问题吗，我现在已经不再尝试复现该代码

这个代码是少文件嘛，from utils.gcn_utils import preprocess_features，from ASAPooling import ASAP_Pooling
from CayleyNet import CayleyConv，这些from后的文件都没有提供，还是我下载的包版本有什么问题嘛？谢谢您的解答

**Comment by zzjkh** [comment]
> > > > 你好，我也在尝试复现该代码，但是对于数据部分有些疑惑，请问实验使用具体的rsfmri数据和预处理流程是什么样的？万分感谢
> > > 
> > > 
> > > 你好我也在复现这个代码，可以加联系方式交流一下吗微信785517067
> > 
> > 
> > 您是遇到了什么问题吗，我现在已经不再尝试复现该代码
> 
> 这个代码是少文件嘛，from utils.gcn_utils import preprocess_features，from ASAPooling import ASAP_Pooling from CayleyNet import CayleyConv，这些from后的文件都没有提供，还是我下载的包版本有什么问题嘛？谢谢您的解答

我复现过程中发现这些代码都是没有在主程序中使用的，直接注释了就可以，我觉得该模型复现的主要问题是数据集的组织处理上。

**Comment by 78551** [comment]
> > > > > 你好，我也在尝试复现该代码，但是对于数据部分有些疑惑，请问实验使用具体的rsfmri数据和预处理流程是什么样的？万分感谢
> > > > 
> > > > 
> > > > 你好我也在复现这个代码，可以加联系方式交流一下吗微信785517067
> > > 
> > > 
> > > 您是遇到了什么问题吗，我现在已经不再尝试复现该代码
> > 
> > 
> > 这个代码是少文件嘛，from utils.gcn_utils import preprocess_features，from ASAPooling import ASAP_Pooling from CayleyNet import CayleyConv，这些from后的文件都没有提供，还是我下载的包版本有什么问题嘛？谢谢您的解答
> 
> 我复现过程中发现这些代码都是没有在主程序中使用的，直接注释了就可以，我觉得该模型复现的主要问题是数据集的组织处理上。

好的好的，十分感谢，数据集的组织处理确实好难，我目前是下载了CPAC处理过的数据集，如果有眉目和您讲

**Comment by 78551** [comment]
> > 非常感谢您的代码，对我学习非常有帮助！想请教您一个问题，该论文采用的是节点特征是每个roi对应的与其他roi皮尔逊相关组成的向量吗，我采用此方法，十折最高只能在测试集上达到70%左右的精度，非常期待您的指导和答复！
> 
> 你好，我也在复现这篇论文，我也只能达到类似的效果，希望我们可以交流交流？ ![image](https://private-user-images.githubusercontent.com/96817690/386973462-3f85b1c6-cb51-4a3f-8a1e-e5443fef545b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NTEzMjYsIm5iZiI6MTczNDk1MTAyNiwicGF0aCI6Ii85NjgxNzY5MC8zODY5NzM0NjItM2Y4NWIxYzYtY2I1MS00YTNmLThhMWUtZTU0NDNmZWY1NDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDEwNTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NjJlMDA3MDk3ODBmYTg3MDBjNjU2YjAxMjU3YTgyZDZhZTM5ZTA2NGY0N2FiZjM4ODY3NDIxNTVmYTY4NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yX2842LrD6NHLiXNtYGn6hwFVuFtgSjo7v59U0yFflA)

你好，可以分享一下嵌入代码的数据是什么样子的吗？是图像还是bold序列还是什么呀

**Comment by 78551** [comment]
> 非常感谢您的代码，对我学习非常有帮助！想请教您一个问题，该论文采用的是节点特征是每个roi对应的与其他roi皮尔逊相关组成的向量吗，我采用此方法，十折最高只能在测试集上达到70%左右的精度，非常期待您的指导和答复！

你好可以请教代码复现相关的问题吗？

**Comment by wxt12** [comment]
> > 非常感谢您的代码，对我学习非常有帮助！想请教您一个问题，该论文采用的是节点特征是每个roi对应的与其他roi皮尔逊相关组成的向量吗，我采用此方法，十折最高只能在测试集上达到70%左右的精度，非常期待您的指导和答复！
> 
> 你好，我也在复现这篇论文，我也只能达到类似的效果，希望我们可以交流交流？ ![image](https://github.com/user-attachments/assets/3f85b1c6-cb51-4a3f-8a1e-e5443fef545b)

你好可以交流一下复现问题吗，我用ho图谱跑出的结果只有65%，而且在训练过程中训练准确率上升很慢，测试准确率也几乎都在50%上下
